name: Check for translation modifications

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed files
        id: get_changed_files
        uses: tj-actions/changed-files@v1
        with:
          files_ignore: 'en'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.get_changed_files.outputs.files == '' }}Did you mean to modify these translations? Translations should be modified on crowdin
            ${{ steps.get_changed_files.outputs.files }}
            ${{ steps.get_changed_files.outputs.files == '' }}no known flaws
          reactions: "+1"
          allow-reactions: true
          delete-detected: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
