name: Check PR for translations

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v1
        with:
          number: ${{ github.event.number }}
      - name: Check for translations
        if: steps.files.outputs.added != ''
        id: translations
        run: |
          echo "${{ steps.files.outputs.added }}" | while read filename
          do
            if [[ ! $filename =~ ^en/ ]]; then
              echo "::$env(GITHUB_WORKSPACE)::${filename} is a translation and should not be edited." >> comment.txt
              touch .update
            fi
          done
      - name: Check for updates
        if: steps.files.outputs.modified != ''
        id: updates
        run: touch .update
      - name: Comment on PR
        if: steps.files.outputs.added != '' || steps.files.outputs.modified != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            ${{ steps.translations.outputs.comment }}${{ steps.updates.outputs.comment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATE: ${{ fileExists('.update') }}
