name: Check for translation modifications

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        # Get changed files that are not in /en
        id: get_changed_files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.md
          files_ignore: 'en'

      - name: Split changed files
        id: split_files
        run: |
          CHANGED_FILES=(${{ steps.assign_files.outputs.changed_files }})  # Convert output to array
          echo "::set-output name=split_files::${CHANGED_FILES[*]}"  # Join array with spaces
        shell: bash

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Found flaws

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Found flaws
            {% for file in {{ steps.split_files.outputs.split_files }} %}
            - {{ file }} - ERROR: Only modify transations in crowdin
            {% endfor %}
          edit-mode: replace
