
name: Check PR for non-English changes

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v1
        with:
          files_ignore: en/**
      - name: Check for non-English changes
        id: non-english-changes
        run: |
          changed_files=$(echo "${{ steps.files.outputs.all }}" | tr '\n' ' ')
          non_en_files=$(grep -v '^en/' <<< "$changed_files")
          if [[ -n "$non_en_files" ]]; then
            echo "::set-output name=files::${non_en_files}"
            echo "::set-output name=update::true"
          fi
      - name: Comment on PR
        if: steps.non-english-changes.outputs.files != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            Did you mean to edit these translations? Translations should be updated in www.fred.jim:
            ```
            ${{ steps.non-english-changes.outputs.files }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATE: ${{ steps.non-english-changes.outputs.update || false }}
      - name: Comment on PR
        if: steps.non-english-changes.outputs.files == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            No known flaws in PR.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATE: ${{ steps.non-english-changes.outputs.update || false }}
