name: Check for modified translations

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        uses: tj-actions/changed-files@v1
        with:
          files_ignore: 'en/**'
        id: changed-files

      - name: Check for modified translations
        run: |
          files=$(echo "${{ steps.changed-files.outputs.files }}" | grep -v '^en/')
          if [ -z "$files" ]; then
            echo "No modified translations found."
            comment_body="No known flaws."
          else
            echo "Modified translations found:"
            echo "$files"
            comment_body="Did you mean to modify these translations? Translations should be modified on crowdin.\n\n$files"
          fi

          echo "::set-output name=comment-body::$comment_body"

      - name: Add or update PR comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.check_translations.outputs.comment-body }}
          token: ${{ secrets.GITHUB_TOKEN }}
