name: Check PR for non-English changes

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v1
        with:
          files_ignore: en/**
      - name: Check for non-English changes
        id: non-english-changes
        run: |
          changed_files=$(echo "${{ steps.files.outputs.all }}" | tr '\n' ' ')
          non_en_files=$(grep -v '^en/' <<< "$changed_files")
          if [[ -n "$non_en_files" ]]; then
            echo "::set-output name=files::${non_en_files}"
            echo "::set-output name=update::true"
          fi
      - name: Create comment on PR
        if: steps.non-english-changes.outputs.files != '' && steps.non-english-changes.outputs.update != 'true'
        uses: peter-evans/create-issue-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Did you mean to edit these translations? Translations should be updated in www.fred.jim:
            ```
            ${{ steps.non-english-changes.outputs.files }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update comment on PR
        if: steps.non-english-changes.outputs.files != '' && steps.non-english-changes.outputs.update == 'true'
        uses: peter-evans/update-issue-comment@v1
        with:
          comment-id: ${{ github.event.pull_request.body | jq -r '.comments[] | select(.body | contains("Did you mean to edit these translations? Translations should be updated in www.fred.jim:")) | .id' }}
          body: |
            Did you mean to edit these translations? Translations should be updated in www.fred.jim:
            ```
            ${{ steps.non-english-changes.outputs.files }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create comment on PR
        if: steps.non-english-changes.outputs.files == '' && steps.non-english-changes.outputs.update != 'true'
        uses: peter-evans/create-issue-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            No known flaws in PR.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update comment on PR
        if: steps.non-english-changes.outputs.files == '' && steps.non-english-changes.outputs.update == 'true'
        uses: peter-evans/update-issue-comment@v1
        with:
          comment-id: ${{ github.event.pull_request.body | jq -r '.comments[] | select(.body | contains("No known flaws in PR.")) | .id' }}
          body: |
            No known flaws in PR.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
