name: Check PR links

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Get changed english files
      # Get changed markdown that are in /en
      id: get_changed_markdown_english
      uses: tj-actions/changed-files@v35
      with:
        files: |
          en/**/*.md
          # files_ignore: 'en'

    - name: Run link checker
      id: link-check
      run: |
        npm -g install markdown_link_checker_sc
        mkdir logs
        markdown_link_checker_sc -d ${{ github.workspace }}/en -f ${{ steps.get_changed_markdown_english.outputs.all_changed_files }} >./logs/log.md

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          logs

    - name: Read log.md
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: logs/log.md
        
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}"
      
