name: Check PR links

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install markdown_link_checker_sc@0.0.1
    - name: Run link checker
      run: |
        markdown-link-checker -d ${{ github.workspace }}/en
    - name: Save output
      id: output
      run: echo "::set-output name=check_output::$(cat output.txt)"
      shell: bash
    - name: Show output
      run: echo "${{ steps.output.outputs.check_output }}"
