name: Check PR links

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm ci
    - run: npm test
      
    - name: Run link checker
      run: |
        markdown_link_checker_sc -d ${{ github.workspace }}/en
    - name: Save output
      id: output
      run: echo "::set-output name=check_output::$(cat output.txt)"
      shell: bash
    - name: Show output
      run: echo "${{ steps.output.outputs.check_output }}"
