name: Check PR links

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      
    - name: Run link checker
      id: link-check
      run: |
        #npm -g install markdown_link_checker_sc
        echo "cabage=thingy" >> $GITHUB_ENV
        
        output=$(markdown_link_checker_sc -d ${{ github.workspace }}/en)
        echo "linkcheck=${output}" >> $GITHUB_ENV
        # markdown_link_checker_sc -d ${{ github.workspace }}/en
           
    - name: Use output
      run: |
        echo "Output1: ${{ env.cabage}}"
        echo "Output2: ${{ env.OUTPUT }}"
