name: Check PR links

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Get changed english files
      # Get changed markdown that are in /en
      id: get_changed_markdown_english
      uses: tj-actions/changed-files@v35
      with:
        json_raw_format: true
        write_output_files: true
        files: |
          en/**/*.md

    #- name: Verify the contents of the .github/outputs/added_files.json file
    #  run: |
    #    cat .github/outputs/added_files.json

    #- name: Try copy.github/outputs/added_files.json file
    #  run: |
    #    mkdir logs
    #    cat .github/outputs/added_files.json
    #    cp .github/outputs/added_files.json ./logs/added_files.log
               
    - name: Echo changed files to file from json output
      run: |
        echo "${{ steps.get_changed_markdown_english.outputs.all_changed_files }}" 
        echo "${{ steps.get_changed_markdown_english.outputs.all_changed_files }} > ./logs/log2.md"
        
    - name: Run link checker
      id: link-check
      run: |
        npm -g install markdown_link_checker_sc
        #mkdir logs
        markdown_link_checker_sc -d ${{ github.workspace }}/en -f ${{ steps.get_changed_markdown_english.outputs.all_changed_files }} -- | tee ./logs/log1.md
        #markdown_link_checker_sc -f ${{ steps.get_changed_markdown_english.outputs.all_changed_files }} -d ${{ github.workspace }}/en -- | tee ./logs/log2.md
        #markdown_link_checker_sc -d /home/runner/work/PX4-user_guide/PX4-user_guide/en -f en/advanced/computer_vision.md en/frames_rover/README.md en/test_cards/mc_04_failsafe_testing.md -- | tee ./logs/log3.md
        #markdown_link_checker_sc -d ${{ github.workspace }}/en -f ${{ steps.get_changed_markdown_english_two.outputs.all_changed_files }} -- | tee ./logs/log4.md
        ##markdown_link_checker_sc -d ${{ github.workspace }}/en | tee ./logs/log2.md
        #markdown_link_checker_sc -d ${{ github.workspace }}/en -f ${{ steps.get_changed_markdown_english.outputs.all_changed_files }} -- > ./logs/log3.md
        #markdown_link_checker_sc -d ${{ github.workspace }}/en > ./logs/log4.md
        #markdown_link_checker_sc -d ${{ github.workspace }}/en | tee ./logs/log5.md
        #markdown_link_checker_sc -d ${{ github.workspace }}/en -f ${{ steps.get_changed_markdown_english.outputs.all_changed_files }} -- &> ./logs/log6.md        
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          logs

    - name: Read log.md
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./logs/log2.md
        
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}"
      
