name: Comment Workflow
on:
  workflow_run:
    workflows: ["Check for flaws"]
    types:
      - completed
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # Would like to do this, but it doesn't work (for me).
      # Moving to time-based, or triggering on workflow 
      #- name: Wait for artifacts upload to succeed
      #  uses: lewagon/wait-on-check-action@v1.3.1
      #  with:
      #    ref: ${{ github.ref }}
      #    check-name: 'Archive production artifacts'
      #    repo-token: ${{ secrets.GITHUB_TOKEN }}
      #    wait-interval: 80

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"  
        
      #- name: Sleep for 80 seconds
      #  run: sleep 80s
      #  shell: bash
  
      #- name: Get artifacts from flaw checker workflow
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: logs_and_errors
      #    #path: ./logs
          
      #- name: Read errorsFilteredByPrPages.md file
      #  id: read-errors-by-page
      #  uses: juliangruber/read-file-action@v1
      #  with:
      #    path: ./logs/errorsFilteredByPrPages.md

      #- name: Echo Errors by Page
      #  run: echo "${{ steps.read-errors-by-page.outputs.content }}"
        
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Flaws

      #- name: Create or update comment
      #  uses: peter-evans/create-or-update-comment@v3
      #  with:
      #    comment-id: ${{ steps.fc.outputs.comment-id }}
      #    issue-number: ${{ github.event.pull_request.number }}
      #    body: |
      #      Flaws
      #      ${{ steps.read-errors-by-page.outputs.content }}
      #    edit-mode: replace
          
